
INFO 2023-10-02 12:14:02,429 views 2308 6012 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-02 12:14:02,430 basehttp 2308 6012 "GET / HTTP/1.1" 200 548
INFO 2023-10-02 12:14:50,972 autoreload 2308 7392 C:\Users\Менеджер\Desktop\Python\Django\myproject\myapp\views.py changed, reloading.
INFO 2023-10-02 12:14:51,848 autoreload 4392 5244 Watching for file changes with StatReloader
INFO 2023-10-02 12:14:52,934 views 4392 5524 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-02 12:14:52,935 basehttp 4392 5524 "GET / HTTP/1.1" 200 548
INFO 2023-10-02 12:14:59,224 views 4392 5524 Показана информация: <h1>About us</h1>
INFO 2023-10-02 12:14:59,225 basehttp 4392 5524 "GET /about/ HTTP/1.1" 200 17
INFO 2023-10-02 12:15:36,209 autoreload 4392 5244 C:\Users\Менеджер\Desktop\Python\Django\myproject\myapp\views.py changed, reloading.
INFO 2023-10-02 12:15:37,237 autoreload 2884 1812 Watching for file changes with StatReloader
INFO 2023-10-02 12:15:37,538 views 2884 4792 Показана информация: <h1>About us</h1><p>Страница о нас</p>
INFO 2023-10-02 12:15:37,538 basehttp 2884 4792 "GET /about/ HTTP/1.1" 200 50
INFO 2023-10-03 10:15:03,377 autoreload 5780 8944 Watching for file changes with StatReloader
INFO 2023-10-03 10:15:06,171 views 5780 5448 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-03 10:15:06,172 basehttp 5780 5448 "GET / HTTP/1.1" 200 548
WARNING 2023-10-03 10:15:06,620 log 5780 5448 Not Found: /favicon.ico
WARNING 2023-10-03 10:15:06,626 basehttp 5780 5448 "GET /favicon.ico HTTP/1.1" 404 2441
INFO 2023-10-03 14:05:07,493 autoreload 9540 11924 Watching for file changes with StatReloader
INFO 2023-10-03 14:05:38,325 autoreload 8516 15128 Watching for file changes with StatReloader
INFO 2023-10-03 14:05:41,779 views 8516 7896 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-03 14:05:41,780 basehttp 8516 7896 "GET / HTTP/1.1" 200 548
WARNING 2023-10-03 14:05:42,016 log 8516 7896 Not Found: /favicon.ico
WARNING 2023-10-03 14:05:42,050 basehttp 8516 7896 "GET /favicon.ico HTTP/1.1" 404 2441
INFO 2023-10-03 14:05:55,160 views 8516 3764 Показана информация: <h1>About us</h1><p>Страница о нас</p>
INFO 2023-10-03 14:05:55,160 basehttp 8516 3764 "GET /about/ HTTP/1.1" 200 50
INFO 2023-10-03 16:53:34,625 autoreload 10128 6092 Watching for file changes with StatReloader
INFO 2023-10-03 16:53:37,534 views 10128 5752 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-03 16:53:37,536 basehttp 10128 5752 "GET / HTTP/1.1" 200 548
WARNING 2023-10-03 16:53:37,669 log 10128 5752 Not Found: /favicon.ico
WARNING 2023-10-03 16:53:37,670 basehttp 10128 5752 "GET /favicon.ico HTTP/1.1" 404 2441
INFO 2023-10-04 13:48:53,527 autoreload 6208 11924 Watching for file changes with StatReloader
INFO 2023-10-04 13:49:14,679 views 6208 268 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 13:49:14,680 basehttp 6208 268 "GET / HTTP/1.1" 200 548
WARNING 2023-10-04 13:49:14,816 log 6208 268 Not Found: /favicon.ico
WARNING 2023-10-04 13:49:14,817 basehttp 6208 268 "GET /favicon.ico HTTP/1.1" 404 2546
WARNING 2023-10-04 13:49:22,860 log 6208 14520 Not Found: /les3/
WARNING 2023-10-04 13:49:22,860 basehttp 6208 14520 "GET /les3/ HTTP/1.1" 404 2528
ERROR 2023-10-04 13:49:32,457 log 6208 5420 Internal Server Error: /les2/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 5, in my_view
    return render(request, "myapp2/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-10-04 13:49:32,474 basehttp 6208 5420 "GET /les2/ HTTP/1.1" 500 128865
ERROR 2023-10-04 13:52:38,513 log 6208 11800 Internal Server Error: /les2/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 5, in my_view
    return render(request, "myapp2/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-10-04 13:52:38,525 basehttp 6208 11800 "GET /les2/ HTTP/1.1" 500 129002
INFO 2023-10-04 13:53:28,229 basehttp 6208 9300 "GET /les2/ HTTP/1.1" 200 33
WARNING 2023-10-04 13:55:20,530 log 6208 11432 Not Found: /les3/
WARNING 2023-10-04 13:55:20,532 basehttp 6208 11432 "GET /les3/ HTTP/1.1" 404 2528
ERROR 2023-10-04 13:55:26,198 log 6208 11928 Internal Server Error: /les2/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 5, in my_view
    return render(request, "myapp2/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-10-04 13:55:26,220 basehttp 6208 11928 "GET /les2/ HTTP/1.1" 500 128928
INFO 2023-10-04 13:58:05,705 autoreload 444 2304 Watching for file changes with StatReloader
INFO 2023-10-04 13:58:07,934 views 444 2360 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 13:58:07,938 basehttp 444 2360 "GET / HTTP/1.1" 200 548
ERROR 2023-10-04 13:58:18,690 log 444 2360 Internal Server Error: /les2/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 5, in my_view
    return render(request, "myapp2/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '('index')' from 'url_for('index')'
ERROR 2023-10-04 13:58:18,716 basehttp 444 2360 "GET /les2/ HTTP/1.1" 500 171823
INFO 2023-10-04 13:59:30,877 basehttp 444 10512 "GET /les2/ HTTP/1.1" 200 2125
WARNING 2023-10-04 13:59:30,915 basehttp 444 10512 "GET /static/style.css HTTP/1.1" 404 1786
INFO 2023-10-04 14:01:38,748 basehttp 444 9040 "GET /les2/ HTTP/1.1" 200 2125
WARNING 2023-10-04 14:01:38,789 basehttp 444 9040 "GET /static/style.css HTTP/1.1" 404 1786
INFO 2023-10-04 14:01:40,680 basehttp 444 9736 "GET /les2/ HTTP/1.1" 200 2125
WARNING 2023-10-04 14:01:40,714 basehttp 444 9736 "GET /static/style.css HTTP/1.1" 404 1786
INFO 2023-10-04 14:01:45,048 views 444 13796 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 14:01:45,049 basehttp 444 13796 "GET / HTTP/1.1" 200 548
INFO 2023-10-04 14:01:50,403 basehttp 444 13796 "GET /les2/ HTTP/1.1" 200 2125
WARNING 2023-10-04 14:01:50,693 basehttp 444 13796 "GET /static/style.css HTTP/1.1" 404 1786
INFO 2023-10-04 14:02:20,521 basehttp 444 9516 "GET /les2/ HTTP/1.1" 200 2125
WARNING 2023-10-04 14:02:20,567 basehttp 444 9516 "GET /static/style.css HTTP/1.1" 404 1786
INFO 2023-10-04 14:02:21,380 basehttp 444 12692 "GET /les2/ HTTP/1.1" 200 2125
WARNING 2023-10-04 14:02:21,416 basehttp 444 12692 "GET /static/style.css HTTP/1.1" 404 1786
INFO 2023-10-04 14:02:21,716 basehttp 444 2756 "GET /les2/ HTTP/1.1" 200 2125
WARNING 2023-10-04 14:02:21,758 basehttp 444 2756 "GET /static/style.css HTTP/1.1" 404 1786
INFO 2023-10-04 14:02:21,955 basehttp 444 12748 "GET /les2/ HTTP/1.1" 200 2125
WARNING 2023-10-04 14:02:21,992 basehttp 444 12748 "GET /static/style.css HTTP/1.1" 404 1786
WARNING 2023-10-04 14:02:26,843 basehttp 444 12624 "GET /static/style.css HTTP/1.1" 404 1786
INFO 2023-10-04 14:03:21,748 basehttp 444 9776 "GET /les2/ HTTP/1.1" 200 2125
WARNING 2023-10-04 14:03:21,800 basehttp 444 9776 "GET /static/style.css HTTP/1.1" 404 1786
INFO 2023-10-04 14:03:26,986 basehttp 444 7440 "GET /les2/ HTTP/1.1" 200 2125
WARNING 2023-10-04 14:03:27,035 basehttp 444 7440 "GET /static/style.css HTTP/1.1" 404 1786
INFO 2023-10-04 14:03:33,068 basehttp 444 6816 "GET /les2/ HTTP/1.1" 200 2125
WARNING 2023-10-04 14:03:33,102 basehttp 444 6816 "GET /static/style.css HTTP/1.1" 404 1786
INFO 2023-10-04 14:05:11,808 autoreload 8936 12996 Watching for file changes with StatReloader
INFO 2023-10-04 14:05:47,075 views 8936 12624 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 14:05:47,082 basehttp 8936 12624 "GET / HTTP/1.1" 200 548
INFO 2023-10-04 14:05:54,080 basehttp 8936 12624 "GET /les2/ HTTP/1.1" 200 2125
INFO 2023-10-04 14:05:54,226 basehttp 8936 12624 "GET /static/style.css HTTP/1.1" 200 5907
INFO 2023-10-04 14:05:54,250 basehttp 8936 5740 "GET /static/side_top.png HTTP/1.1" 200 1318
INFO 2023-10-04 14:05:54,252 basehttp 8936 12624 "GET /static/banner.jpg HTTP/1.1" 200 13040
INFO 2023-10-04 14:05:54,256 basehttp 8936 10220 "GET /static/side_back.png HTTP/1.1" 200 155
INFO 2023-10-04 14:06:43,085 autoreload 6112 6376 Watching for file changes with StatReloader
INFO 2023-10-04 14:06:44,723 views 6112 1008 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 14:06:44,726 basehttp 6112 1008 "GET / HTTP/1.1" 200 548
INFO 2023-10-04 14:06:50,497 basehttp 6112 1008 "GET /les2/ HTTP/1.1" 200 2125
ERROR 2023-10-04 14:07:24,583 log 6112 1008 Internal Server Error: /les2/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 5, in my_view
    return render(request, "myapp2/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-10-04 14:07:24,604 basehttp 6112 1008 "GET /les2/ HTTP/1.1" 500 129065
INFO 2023-10-04 14:08:42,134 autoreload 6112 6376 C:\Users\msv99\Desktop\Python\Django\Homework\myproject\settings.py changed, reloading.
INFO 2023-10-04 14:08:45,378 autoreload 14464 3864 Watching for file changes with StatReloader
ERROR 2023-10-04 14:09:05,531 log 14464 12632 Internal Server Error: /les2/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 5, in my_view
    return render(request, "myapp2/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-10-04 14:09:05,552 basehttp 14464 12632 "GET /les2/ HTTP/1.1" 500 129065
ERROR 2023-10-04 14:09:06,492 log 14464 12632 Internal Server Error: /les2/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 5, in my_view
    return render(request, "myapp2/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-10-04 14:09:06,510 basehttp 14464 12632 "GET /les2/ HTTP/1.1" 500 129065
INFO 2023-10-04 14:09:16,726 autoreload 14464 3864 C:\Users\msv99\Desktop\Python\Django\Homework\myproject\settings.py changed, reloading.
INFO 2023-10-04 14:09:18,344 autoreload 388 13804 Watching for file changes with StatReloader
ERROR 2023-10-04 14:10:30,340 log 388 14640 Internal Server Error: /les2/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 5, in my_view
    return render(request, "myapp2/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-10-04 14:10:30,354 basehttp 388 14640 "GET /les2/ HTTP/1.1" 500 129065
ERROR 2023-10-04 14:10:33,147 log 388 14640 Internal Server Error: /les2/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 5, in my_view
    return render(request, "myapp2/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-10-04 14:10:33,177 basehttp 388 14640 "GET /les2/ HTTP/1.1" 500 129065
INFO 2023-10-04 14:10:44,562 autoreload 8692 10336 Watching for file changes with StatReloader
INFO 2023-10-04 14:10:46,243 views 8692 8448 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 14:10:46,246 basehttp 8692 8448 "GET / HTTP/1.1" 200 548
ERROR 2023-10-04 14:10:52,356 log 8692 8448 Internal Server Error: /les2/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 5, in my_view
    return render(request, "myapp2/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-10-04 14:10:52,384 basehttp 8692 8448 "GET /les2/ HTTP/1.1" 500 129058
INFO 2023-10-04 14:13:30,413 autoreload 1112 15036 Watching for file changes with StatReloader
INFO 2023-10-04 14:13:32,320 views 1112 6376 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 14:13:32,324 basehttp 1112 6376 "GET / HTTP/1.1" 200 548
ERROR 2023-10-04 14:13:38,477 log 1112 6376 Internal Server Error: /les2/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 5, in my_view
    return render(request, "myapp2/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-10-04 14:13:38,498 basehttp 1112 6376 "GET /les2/ HTTP/1.1" 500 128928
INFO 2023-10-04 14:16:08,062 autoreload 1112 15036 C:\Users\msv99\Desktop\Python\Django\Homework\myproject\settings.py changed, reloading.
INFO 2023-10-04 14:16:09,420 autoreload 1728 992 Watching for file changes with StatReloader
INFO 2023-10-04 14:16:11,403 views 1728 2632 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 14:16:11,406 basehttp 1728 2632 "GET / HTTP/1.1" 200 548
ERROR 2023-10-04 14:16:17,059 log 1728 2632 Internal Server Error: /les2/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 5, in my_view
    return render(request, "myapp2/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-10-04 14:16:17,082 basehttp 1728 2632 "GET /les2/ HTTP/1.1" 500 129058
INFO 2023-10-04 14:17:47,247 autoreload 1728 992 C:\Users\msv99\Desktop\Python\Django\Homework\myproject\settings.py changed, reloading.
INFO 2023-10-04 14:17:48,858 autoreload 8176 12520 Watching for file changes with StatReloader
INFO 2023-10-04 14:17:51,905 basehttp 8176 12340 "GET /les2/ HTTP/1.1" 200 2125
INFO 2023-10-04 14:17:55,897 basehttp 8176 12340 "GET /les2/ HTTP/1.1" 200 2125
INFO 2023-10-04 14:17:58,024 basehttp 8176 12340 "GET /les2/ HTTP/1.1" 200 2125
INFO 2023-10-04 14:17:58,506 basehttp 8176 12340 "GET /les2/ HTTP/1.1" 200 2125
INFO 2023-10-04 14:17:59,037 basehttp 8176 12340 "GET /les2/ HTTP/1.1" 200 2125
INFO 2023-10-04 14:24:04,799 autoreload 8176 12520 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-04 14:24:06,434 autoreload 7524 11460 Watching for file changes with StatReloader
INFO 2023-10-04 14:25:57,100 autoreload 7524 11460 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-04 14:25:58,724 autoreload 10352 12240 Watching for file changes with StatReloader
INFO 2023-10-04 14:32:29,148 autoreload 10352 12240 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\urls.py changed, reloading.
INFO 2023-10-04 14:32:31,264 autoreload 456 5636 Watching for file changes with StatReloader
INFO 2023-10-04 14:32:32,425 views 456 11920 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 14:32:32,427 basehttp 456 11920 "GET / HTTP/1.1" 200 548
INFO 2023-10-04 14:32:38,608 basehttp 456 11920 "GET /les2/ HTTP/1.1" 200 2125
INFO 2023-10-04 14:32:42,705 basehttp 456 11920 "GET /les2/test HTTP/1.1" 301 0
ERROR 2023-10-04 14:32:42,821 log 456 12692 Internal Server Error: /les2/test/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: test_test() missing 1 required positional argument: 'user_id'
ERROR 2023-10-04 14:32:42,826 basehttp 456 12692 "GET /les2/test/ HTTP/1.1" 500 62129
INFO 2023-10-04 14:33:43,731 autoreload 456 5636 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\urls.py changed, reloading.
INFO 2023-10-04 14:33:45,209 autoreload 7416 8320 Watching for file changes with StatReloader
INFO 2023-10-04 14:34:00,952 autoreload 7416 8320 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\urls.py changed, reloading.
INFO 2023-10-04 14:34:02,347 autoreload 14856 13080 Watching for file changes with StatReloader
ERROR 2023-10-04 14:34:11,486 log 14856 11640 Internal Server Error: /les2/test/28/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 10, in test_test
    user = get_object_or_404(User, pk=user_id)
           ^^^^^^^^^^^^^^^^^
NameError: name 'get_object_or_404' is not defined
ERROR 2023-10-04 14:34:11,491 basehttp 14856 11640 "GET /les2/test/28/ HTTP/1.1" 500 65269
ERROR 2023-10-04 14:34:24,341 log 14856 11640 Internal Server Error: /les2/test/30/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 10, in test_test
    user = get_object_or_404(User, pk=user_id)
           ^^^^^^^^^^^^^^^^^
NameError: name 'get_object_or_404' is not defined
ERROR 2023-10-04 14:34:24,350 basehttp 14856 11640 "GET /les2/test/30/ HTTP/1.1" 500 65269
ERROR 2023-10-04 14:34:30,542 log 14856 11640 Internal Server Error: /les2/test/18/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 10, in test_test
    user = get_object_or_404(User, pk=user_id)
           ^^^^^^^^^^^^^^^^^
NameError: name 'get_object_or_404' is not defined
ERROR 2023-10-04 14:34:30,546 basehttp 14856 11640 "GET /les2/test/18/ HTTP/1.1" 500 65269
INFO 2023-10-04 14:36:25,020 autoreload 14856 13080 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-04 14:36:27,085 autoreload 516 12592 Watching for file changes with StatReloader
ERROR 2023-10-04 14:36:31,894 log 516 824 Internal Server Error: /les2/test/18/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 12, in test_test
    order = Order.objects.filter(user=user).order_by('-id')[:5]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2023-10-04 14:36:31,903 basehttp 516 824 "GET /les2/test/18/ HTTP/1.1" 500 125223
ERROR 2023-10-04 14:36:41,768 log 516 824 Internal Server Error: /les2/test/30/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 12, in test_test
    order = Order.objects.filter(user=user).order_by('-id')[:5]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2023-10-04 14:36:41,778 basehttp 516 824 "GET /les2/test/30/ HTTP/1.1" 500 125086
INFO 2023-10-04 14:38:51,565 autoreload 516 12592 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-04 14:38:53,209 autoreload 2592 1212 Watching for file changes with StatReloader
ERROR 2023-10-04 14:38:57,487 log 2592 12096 Internal Server Error: /les2/test/30/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    return render(request, 'myapp3/index2.html', {'user':user,})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/index2.html
ERROR 2023-10-04 14:38:57,494 basehttp 2592 12096 "GET /les2/test/30/ HTTP/1.1" 500 80696
INFO 2023-10-04 14:41:30,030 autoreload 2592 1212 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-04 14:41:31,629 autoreload 12440 4412 Watching for file changes with StatReloader
INFO 2023-10-04 14:46:57,393 autoreload 9932 8496 Watching for file changes with StatReloader
INFO 2023-10-04 14:46:59,557 views 9932 1248 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 14:46:59,561 basehttp 9932 1248 "GET / HTTP/1.1" 200 548
INFO 2023-10-04 14:47:04,548 basehttp 9932 1248 "GET /les2/ HTTP/1.1" 200 2125
INFO 2023-10-04 14:47:13,815 basehttp 9932 1248 "GET /les2/test/30 HTTP/1.1" 301 0
ERROR 2023-10-04 14:47:14,015 log 9932 13780 Internal Server Error: /les2/test/30/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    return render(request, 'myapp3/index2.html', {'user':user})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/index2.html
ERROR 2023-10-04 14:47:14,032 basehttp 9932 13780 "GET /les2/test/30/ HTTP/1.1" 500 80555
ERROR 2023-10-04 14:48:20,773 log 9932 13780 Internal Server Error: /les2/test/30/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    return render(request, 'myapp3/index2.html', {'user':user})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/index2.html
ERROR 2023-10-04 14:48:20,782 basehttp 9932 13780 "GET /les2/test/30/ HTTP/1.1" 500 80692
INFO 2023-10-04 14:58:37,822 autoreload 9932 8496 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-04 14:58:39,673 autoreload 8148 9644 Watching for file changes with StatReloader
ERROR 2023-10-04 14:58:40,339 log 8148 14820 Internal Server Error: /les2/test/30/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    return render(request, 'myapp3/index2.html', {'user':user.name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/index2.html
ERROR 2023-10-04 14:58:40,348 basehttp 8148 14820 "GET /les2/test/30/ HTTP/1.1" 500 80562
ERROR 2023-10-04 14:59:26,064 log 8148 14820 Internal Server Error: /les2/test/30/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    return render(request, 'myapp3/index2.html', {'user':user.name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/index2.html
ERROR 2023-10-04 14:59:26,076 basehttp 8148 14820 "GET /les2/test/30/ HTTP/1.1" 500 80562
ERROR 2023-10-04 14:59:31,390 log 8148 14820 Internal Server Error: /les2/test/31/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    return render(request, 'myapp3/index2.html', {'user':user.name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/index2.html
ERROR 2023-10-04 14:59:31,401 basehttp 8148 14820 "GET /les2/test/31/ HTTP/1.1" 500 80425
ERROR 2023-10-04 15:00:10,740 log 8148 14820 Internal Server Error: /les2/test/31/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    return render(request, 'myapp3/index2.html', {'user':user.name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/index2.html
ERROR 2023-10-04 15:00:10,746 basehttp 8148 14820 "GET /les2/test/31/ HTTP/1.1" 500 80562
ERROR 2023-10-04 15:00:11,538 log 8148 14820 Internal Server Error: /les2/test/31/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    return render(request, 'myapp3/index2.html', {'user':user.name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/index2.html
ERROR 2023-10-04 15:00:11,544 basehttp 8148 14820 "GET /les2/test/31/ HTTP/1.1" 500 80562
ERROR 2023-10-04 15:00:12,306 log 8148 14820 Internal Server Error: /les2/test/31/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    return render(request, 'myapp3/index2.html', {'user':user.name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/index2.html
ERROR 2023-10-04 15:00:12,315 basehttp 8148 14820 "GET /les2/test/31/ HTTP/1.1" 500 80562
ERROR 2023-10-04 15:00:31,799 log 8148 14820 Internal Server Error: /les2/test/31/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    return render(request, 'myapp3/index2.html', {'user':user.name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/index2.html
ERROR 2023-10-04 15:00:31,806 basehttp 8148 14820 "GET /les2/test/31/ HTTP/1.1" 500 80562
ERROR 2023-10-04 15:00:32,967 log 8148 14820 Internal Server Error: /les2/test/31/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    return render(request, 'myapp3/index2.html', {'user':user.name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/index2.html
ERROR 2023-10-04 15:00:32,972 basehttp 8148 14820 "GET /les2/test/31/ HTTP/1.1" 500 80562
INFO 2023-10-04 15:01:02,326 autoreload 8148 9644 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-04 15:01:04,063 autoreload 4796 9212 Watching for file changes with StatReloader
INFO 2023-10-04 15:01:04,543 basehttp 4796 8996 "GET /les2/test/31/ HTTP/1.1" 200 2145
INFO 2023-10-04 15:01:36,366 basehttp 4796 8996 "GET /les2/test/31/ HTTP/1.1" 200 2149
INFO 2023-10-04 15:01:51,858 basehttp 4796 8996 "GET /les2/test/33/ HTTP/1.1" 200 2149
INFO 2023-10-04 15:02:00,266 basehttp 4796 8996 "GET /les2/test/29/ HTTP/1.1" 200 2150
INFO 2023-10-04 15:02:10,097 basehttp 4796 8996 "GET /les2/test/45/ HTTP/1.1" 200 2150
INFO 2023-10-04 15:02:16,342 basehttp 4796 8996 "GET /les2/test/9/ HTTP/1.1" 200 2149
INFO 2023-10-04 15:02:47,098 basehttp 4796 8996 "GET /les2/test/9/ HTTP/1.1" 200 2146
INFO 2023-10-04 15:02:49,203 basehttp 4796 8996 "GET /les2/test/9/ HTTP/1.1" 200 2146
INFO 2023-10-04 15:02:57,962 basehttp 4796 8996 "GET /les2/test/30/ HTTP/1.1" 200 2146
INFO 2023-10-04 15:03:06,911 basehttp 4796 8996 "GET /les2/test/30/ HTTP/1.1" 200 2149
INFO 2023-10-04 15:03:07,679 basehttp 4796 8996 "GET /les2/test/30/ HTTP/1.1" 200 2149
INFO 2023-10-04 15:05:30,665 basehttp 4796 8996 "GET /les2/test/30/ HTTP/1.1" 200 2180
ERROR 2023-10-04 15:06:29,617 log 4796 8996 Internal Server Error: /les2/test/30/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    return render(request, 'myapp2/index2.html', {'user':user.name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(user)' from 'type(user)'
ERROR 2023-10-04 15:06:29,641 basehttp 4796 8996 "GET /les2/test/30/ HTTP/1.1" 500 169771
INFO 2023-10-04 15:06:51,980 basehttp 4796 8996 "GET /les2/test/30/ HTTP/1.1" 200 2209
INFO 2023-10-04 15:06:53,135 basehttp 4796 8996 "GET /les2/test/30/ HTTP/1.1" 200 2209
INFO 2023-10-04 15:06:53,848 basehttp 4796 8996 "GET /les2/test/30/ HTTP/1.1" 200 2209
INFO 2023-10-04 15:07:22,016 autoreload 4796 9212 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-04 15:07:24,070 autoreload 8384 12384 Watching for file changes with StatReloader
ERROR 2023-10-04 15:07:24,789 log 8384 15004 Internal Server Error: /les2/test/30/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    return render(request, 'myapp2/index2.html', {'user':user})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\defaulttags.py", line 193, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'User' object is not iterable
ERROR 2023-10-04 15:07:24,810 basehttp 8384 15004 "GET /les2/test/30/ HTTP/1.1" 500 147776
INFO 2023-10-04 15:07:45,719 basehttp 8384 15004 "GET /les2/test/30/ HTTP/1.1" 200 2325
INFO 2023-10-04 15:08:16,373 basehttp 8384 15004 "GET /les2/test/30/ HTTP/1.1" 200 2249
INFO 2023-10-04 15:08:19,474 basehttp 8384 15004 "GET /les2/test/30/ HTTP/1.1" 200 2249
INFO 2023-10-04 15:09:16,340 autoreload 8384 12384 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-04 15:09:18,217 autoreload 13208 3756 Watching for file changes with StatReloader
ERROR 2023-10-04 15:09:19,268 log 13208 7668 Internal Server Error: /les2/test/30/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 12, in test_test
    order = Order.objects.filter(user=user).order_by('-id')[:5]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2023-10-04 15:09:19,284 basehttp 13208 7668 "GET /les2/test/30/ HTTP/1.1" 500 125222
ERROR 2023-10-04 15:09:32,839 log 13208 7668 Internal Server Error: /les2/test/31/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 12, in test_test
    order = Order.objects.filter(user=user).order_by('-id')[:5]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2023-10-04 15:09:32,858 basehttp 13208 7668 "GET /les2/test/31/ HTTP/1.1" 500 125085
INFO 2023-10-04 15:10:04,847 autoreload 13208 3756 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-04 15:10:06,933 autoreload 12588 6984 Watching for file changes with StatReloader
ERROR 2023-10-04 15:10:07,600 log 12588 1152 Internal Server Error: /les2/test/31/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    order = Order.objects.filter(user=user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2023-10-04 15:10:07,622 basehttp 12588 1152 "GET /les2/test/31/ HTTP/1.1" 500 125216
ERROR 2023-10-04 15:10:14,517 log 12588 1152 Internal Server Error: /les2/test/30/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 13, in test_test
    order = Order.objects.filter(user=user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2023-10-04 15:10:14,528 basehttp 12588 1152 "GET /les2/test/30/ HTTP/1.1" 500 125079
INFO 2023-10-04 18:55:49,956 autoreload 13224 13736 Watching for file changes with StatReloader
INFO 2023-10-04 18:55:54,705 views 13224 2604 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 18:55:54,707 basehttp 13224 2604 "GET / HTTP/1.1" 200 548
WARNING 2023-10-04 18:55:55,942 log 13224 2604 Not Found: /favicon.ico
WARNING 2023-10-04 18:55:55,944 basehttp 13224 2604 "GET /favicon.ico HTTP/1.1" 404 2546
INFO 2023-10-04 18:56:09,949 basehttp 13224 13524 "GET /les2/test/30/ HTTP/1.1" 200 2523
INFO 2023-10-04 18:56:34,787 basehttp 13224 9636 "GET /les2/test/32/ HTTP/1.1" 200 2526
INFO 2023-10-04 19:16:40,623 autoreload 8104 5976 Watching for file changes with StatReloader
INFO 2023-10-04 19:16:43,259 views 8104 6532 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 19:16:43,261 basehttp 8104 6532 "GET / HTTP/1.1" 200 548
INFO 2023-10-04 19:16:59,137 basehttp 8104 1972 "GET /les2/basket/30/ HTTP/1.1" 200 2347
INFO 2023-10-04 19:19:24,776 basehttp 8104 3308 "GET /les2/basket/31/ HTTP/1.1" 200 2345
INFO 2023-10-04 19:19:31,792 basehttp 8104 9256 "GET /les2/basket/5/ HTTP/1.1" 200 2176
INFO 2023-10-04 19:19:36,013 basehttp 8104 9256 "GET /les2/basket/15/ HTTP/1.1" 200 2251
INFO 2023-10-04 19:19:43,733 basehttp 8104 9256 "GET /les2/basket/40/ HTTP/1.1" 200 2349
INFO 2023-10-04 19:19:52,953 basehttp 8104 9256 "GET /les2/basket/41/ HTTP/1.1" 200 2348
INFO 2023-10-04 19:20:03,658 basehttp 8104 9256 "GET /les2/basket/42/ HTTP/1.1" 200 2346
INFO 2023-10-04 19:21:07,949 basehttp 8104 9256 "GET /les2/test/42/ HTTP/1.1" 200 2445
INFO 2023-10-04 19:22:53,021 autoreload 8104 5976 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-04 19:22:54,739 autoreload 8624 3248 Watching for file changes with StatReloader
INFO 2023-10-04 19:41:24,484 autoreload 7224 14996 Watching for file changes with StatReloader
INFO 2023-10-04 19:41:34,192 views 7224 13692 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 19:41:34,195 basehttp 7224 13692 "GET / HTTP/1.1" 200 548
INFO 2023-10-04 19:41:46,113 basehttp 7224 13692 "GET /les2/test/30/ HTTP/1.1" 200 2626
INFO 2023-10-04 19:42:06,569 basehttp 7224 13692 "GET /les2/basket/30/ HTTP/1.1" 200 4055
INFO 2023-10-04 19:47:27,499 basehttp 7224 7796 "GET /les2/basket/30/ HTTP/1.1" 200 4242
INFO 2023-10-04 20:37:54,759 basehttp 7224 10168 "GET /les2/basket/30/ HTTP/1.1" 200 4242
INFO 2023-10-04 20:38:01,538 basehttp 7224 10168 "GET /les2/basket/30/ HTTP/1.1" 200 4242
INFO 2023-10-04 20:38:02,364 basehttp 7224 10168 "GET /les2/basket/30/ HTTP/1.1" 200 4242
INFO 2023-10-04 20:42:21,282 views 7224 10168 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-04 20:42:21,286 basehttp 7224 10168 "GET / HTTP/1.1" 200 548
INFO 2023-10-04 20:42:29,869 basehttp 7224 10168 "GET /les2/ HTTP/1.1" 200 2125
INFO 2023-10-04 20:42:33,827 basehttp 7224 10168 "GET /les2/ HTTP/1.1" 200 2125
INFO 2023-10-04 20:42:45,617 basehttp 7224 10168 "GET /les2/basket/30/ HTTP/1.1" 200 4242
INFO 2023-10-04 20:43:59,917 basehttp 7224 10168 "GET /les2/basket/30/ HTTP/1.1" 200 2437
INFO 2023-10-04 20:44:33,356 basehttp 7224 10168 "GET /les2/basket/30/ HTTP/1.1" 200 2485
INFO 2023-10-04 20:44:47,548 basehttp 7224 10168 "GET /les2/basket/31/ HTTP/1.1" 200 2323
INFO 2023-10-04 20:44:54,734 basehttp 7224 10168 "GET /les2/basket/32/ HTTP/1.1" 200 2325
INFO 2023-10-04 20:45:01,178 basehttp 7224 10168 "GET /les2/basket/30/ HTTP/1.1" 200 2485
INFO 2023-10-04 20:45:14,893 basehttp 7224 10168 "GET /les2/test/30/ HTTP/1.1" 200 2164
INFO 2023-10-04 20:45:20,499 basehttp 7224 10168 "GET /les2/test/31/ HTTP/1.1" 200 2164
INFO 2023-10-04 20:45:29,671 basehttp 7224 10168 "GET /les2/basket/30/ HTTP/1.1" 200 2485
INFO 2023-10-04 20:45:49,576 basehttp 7224 10168 "GET /les2/basket/30/ HTTP/1.1" 200 6103
INFO 2023-10-04 20:46:34,625 basehttp 7224 10168 "GET /les2/basket/30/ HTTP/1.1" 200 2485
INFO 2023-10-04 20:47:07,962 basehttp 7224 10168 "GET /les2/basket/30/ HTTP/1.1" 200 6103
INFO 2023-10-05 16:49:31,495 autoreload 11492 10544 Watching for file changes with StatReloader
INFO 2023-10-05 16:49:43,400 views 11492 14768 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-05 16:49:43,402 basehttp 11492 14768 "GET / HTTP/1.1" 200 548
WARNING 2023-10-05 16:49:44,098 log 11492 14768 Not Found: /favicon.ico
WARNING 2023-10-05 16:49:44,111 basehttp 11492 14768 "GET /favicon.ico HTTP/1.1" 404 2546
INFO 2023-10-05 16:49:55,829 basehttp 11492 16124 "GET /les2/basket/30/ HTTP/1.1" 200 12336
INFO 2023-10-05 16:50:09,901 basehttp 11492 16124 "GET /les2/basket/31/ HTTP/1.1" 200 2617
INFO 2023-10-05 16:50:23,309 basehttp 11492 16124 "GET /les2/basket/30/ HTTP/1.1" 200 12336
INFO 2023-10-05 16:52:44,183 autoreload 11492 10544 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 16:52:46,122 autoreload 7524 6548 Watching for file changes with StatReloader
ERROR 2023-10-05 16:52:46,902 log 7524 2824 Internal Server Error: /les2/basket/30/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 23, in basket
    return render(request, 'myapp2/index2.html', {'user': user, 'orders': orders, 'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\defaulttags.py", line 193, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'ManyRelatedManager' object is not iterable
ERROR 2023-10-05 16:52:46,932 basehttp 7524 2824 "GET /les2/basket/30/ HTTP/1.1" 500 191065
INFO 2023-10-05 16:54:04,304 autoreload 7524 6548 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 16:54:06,635 autoreload 12668 9840 Watching for file changes with StatReloader
INFO 2023-10-05 16:54:07,371 basehttp 12668 6840 "GET /les2/basket/30/ HTTP/1.1" 200 12336
INFO 2023-10-05 16:56:38,501 autoreload 12668 9840 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 16:56:40,746 autoreload 1184 9980 Watching for file changes with StatReloader
WARNING 2023-10-05 16:56:43,506 log 1184 13916 Not Found: /les2/basket/30/
WARNING 2023-10-05 16:56:43,508 basehttp 1184 13916 "GET /les2/basket/30/ HTTP/1.1" 404 3011
INFO 2023-10-05 16:56:54,193 basehttp 1184 13916 "GET /les2/all_orders/30/ HTTP/1.1" 200 12336
INFO 2023-10-05 17:07:42,735 autoreload 13148 15036 Watching for file changes with StatReloader
INFO 2023-10-05 17:07:46,667 basehttp 13148 440 "GET /les2/all_orders/30/ HTTP/1.1" 200 12336
INFO 2023-10-05 17:07:51,752 basehttp 13148 440 "GET /les2/all_orders/31/ HTTP/1.1" 200 2617
INFO 2023-10-05 17:08:42,984 autoreload 6160 5364 Watching for file changes with StatReloader
INFO 2023-10-05 17:08:50,975 basehttp 6160 3788 "GET /les2/all_orders/31/ HTTP/1.1" 200 4328
INFO 2023-10-05 17:11:27,444 basehttp 6160 3788 "GET /les2/all_orders/31/ HTTP/1.1" 200 4328
INFO 2023-10-05 17:14:44,660 autoreload 6160 5364 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 17:14:46,392 autoreload 1468 14720 Watching for file changes with StatReloader
INFO 2023-10-05 17:16:07,239 autoreload 1468 14720 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 17:16:09,464 autoreload 15608 5500 Watching for file changes with StatReloader
INFO 2023-10-05 17:16:10,083 basehttp 15608 6076 "GET /les2/all_orders/31/ HTTP/1.1" 200 4328
INFO 2023-10-05 17:16:11,532 basehttp 15608 6076 "GET /les2/all_orders/31/ HTTP/1.1" 200 4328
INFO 2023-10-05 17:25:53,789 autoreload 15608 5500 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 17:25:55,648 autoreload 2296 13148 Watching for file changes with StatReloader
INFO 2023-10-05 17:25:58,355 basehttp 2296 4924 "GET /les2/all_orders/31/ HTTP/1.1" 200 4328
WARNING 2023-10-05 17:26:09,825 log 2296 4924 Not Found: /les2/all_orders_sorted/31/7
WARNING 2023-10-05 17:26:09,825 basehttp 2296 4924 "GET /les2/all_orders_sorted/31/7 HTTP/1.1" 404 3047
INFO 2023-10-05 17:27:59,617 autoreload 2296 13148 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\urls.py changed, reloading.
INFO 2023-10-05 17:28:01,906 autoreload 2260 2664 Watching for file changes with StatReloader
INFO 2023-10-05 17:28:02,753 basehttp 2260 7516 "GET /les2/all_orders_sorted/31/7 HTTP/1.1" 301 0
INFO 2023-10-05 17:28:02,997 basehttp 2260 14120 "GET /les2/all_orders_sorted/31/7/ HTTP/1.1" 200 2179
INFO 2023-10-05 17:28:11,532 basehttp 2260 14120 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 2179
INFO 2023-10-05 17:28:19,300 basehttp 2260 14120 "GET /les2/all_orders_sorted/30/60/ HTTP/1.1" 200 2179
INFO 2023-10-05 17:28:28,037 basehttp 2260 14120 "GET /les2/all_orders_sorted/31/60/ HTTP/1.1" 200 2179
INFO 2023-10-05 17:28:40,804 basehttp 2260 14120 "GET /les2/all_orders/31/ HTTP/1.1" 200 4328
INFO 2023-10-05 17:29:05,147 basehttp 2260 14120 "GET /les2/all_orders/30/ HTTP/1.1" 200 12336
INFO 2023-10-05 17:31:01,063 autoreload 2260 2664 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 17:31:02,898 autoreload 4352 4296 Watching for file changes with StatReloader
INFO 2023-10-05 17:31:14,656 basehttp 4352 3712 "GET /les2/all_orders_sorted/31/60/ HTTP/1.1" 200 2248
INFO 2023-10-05 17:34:18,753 autoreload 4352 4296 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 17:34:20,866 autoreload 596 14180 Watching for file changes with StatReloader
INFO 2023-10-05 17:34:21,216 basehttp 596 10260 "GET /les2/all_orders_sorted/31/60/ HTTP/1.1" 200 2237
INFO 2023-10-05 17:34:40,621 basehttp 596 10260 "GET /les2/all_orders_sorted/31/7/ HTTP/1.1" 200 2237
INFO 2023-10-05 17:34:56,908 views 596 10260 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-05 17:34:56,911 basehttp 596 10260 "GET / HTTP/1.1" 200 548
INFO 2023-10-05 17:35:06,386 basehttp 596 10260 "GET /les2/test/30/ HTTP/1.1" 200 2164
INFO 2023-10-05 17:35:14,406 basehttp 596 10260 "GET /les2/all_orders/31/ HTTP/1.1" 200 4328
INFO 2023-10-05 17:35:34,852 basehttp 596 10260 "GET /les2/all_orders/31/ HTTP/1.1" 200 4328
INFO 2023-10-05 17:35:49,278 basehttp 596 10260 "GET /les2/all_orders_sorted/31/7/ HTTP/1.1" 200 2237
INFO 2023-10-05 17:39:29,230 autoreload 596 14180 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 17:39:31,487 autoreload 13460 14988 Watching for file changes with StatReloader
INFO 2023-10-05 17:39:32,736 basehttp 13460 4736 "GET /les2/all_orders_sorted/31/7/ HTTP/1.1" 200 2259
INFO 2023-10-05 17:39:48,313 basehttp 13460 4736 "GET /les2/all_orders_sorted/31/1/ HTTP/1.1" 200 2257
INFO 2023-10-05 17:41:01,500 basehttp 13460 4736 "GET /les2/all_orders_sorted/31/1/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:41:59,930 autoreload 13460 14988 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 17:42:02,113 autoreload 14840 6976 Watching for file changes with StatReloader
INFO 2023-10-05 17:47:07,772 autoreload 14840 6976 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 17:47:10,784 autoreload 7416 16108 Watching for file changes with StatReloader
INFO 2023-10-05 17:47:27,642 basehttp 7416 5264 "GET /les2/all_orders/31/ HTTP/1.1" 200 4328
INFO 2023-10-05 17:47:29,970 basehttp 7416 5264 "GET /les2/all_orders_sorted/31/1/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:47:31,441 basehttp 7416 5264 "GET /les2/all_orders_sorted/31/1/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:47:36,396 basehttp 7416 5264 "GET /les2/all_orders_sorted/31/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:47:39,551 basehttp 7416 5264 "GET /les2/all_orders_sorted/31/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:47:52,588 basehttp 7416 5264 "GET /les2/all_orders/30/ HTTP/1.1" 200 12336
INFO 2023-10-05 17:48:09,340 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:48:16,120 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/600/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:48:21,946 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/60/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:49:19,841 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/60/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:49:21,309 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/60/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:50:18,493 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/60/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:50:19,653 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/60/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:50:20,306 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/60/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:50:20,585 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/60/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:50:20,763 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/60/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:50:20,963 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/60/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:50:21,151 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/60/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:50:21,336 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/60/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:50:26,651 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:51:08,357 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:51:08,963 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:51:09,203 basehttp 7416 5264 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:52:44,394 autoreload 7416 16108 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 17:52:46,132 autoreload 12040 9184 Watching for file changes with StatReloader
INFO 2023-10-05 17:53:04,302 autoreload 12040 9184 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 17:53:06,622 autoreload 11308 1200 Watching for file changes with StatReloader
INFO 2023-10-05 17:53:12,011 basehttp 11308 13680 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:53:12,918 basehttp 11308 13680 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:53:14,261 basehttp 11308 13680 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:53:14,973 basehttp 11308 13680 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:53:15,391 basehttp 11308 13680 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:53:15,639 basehttp 11308 13680 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:53:15,857 basehttp 11308 13680 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 2228
INFO 2023-10-05 17:54:41,427 autoreload 11308 1200 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 17:54:43,840 autoreload 8676 12604 Watching for file changes with StatReloader
ERROR 2023-10-05 17:54:47,642 log 8676 12592 Internal Server Error: /les2/all_orders_sorted/30/7/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 40, in all_orders_sorted
    return render(request, 'myapp2/all_orders_sorted.html', {'user': user,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\defaulttags.py", line 193, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'Product' object is not iterable
ERROR 2023-10-05 17:54:47,680 basehttp 8676 12592 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 500 285426
INFO 2023-10-05 17:59:30,929 basehttp 8676 1856 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 33062
INFO 2023-10-05 18:00:01,005 basehttp 8676 1856 "GET /les2/all_orders_sorted/30/1/ HTTP/1.1" 200 17465
INFO 2023-10-05 18:00:31,285 basehttp 8676 1856 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 33062
ERROR 2023-10-05 18:01:10,876 log 8676 1856 Internal Server Error: /les2/all_orders_sorted/30/10/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 40, in all_orders_sorted
    return render(request, 'myapp2/all_orders_sorted.html', {'user': user,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\defaulttags.py", line 193, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'Product' object is not iterable
ERROR 2023-10-05 18:01:10,894 basehttp 8676 1856 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 500 285441
INFO 2023-10-05 18:01:29,573 basehttp 8676 1856 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 17462
INFO 2023-10-05 18:01:50,462 basehttp 8676 1856 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 15350
INFO 2023-10-05 18:01:51,542 basehttp 8676 1856 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 15350
INFO 2023-10-05 18:01:52,215 basehttp 8676 1856 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 15350
INFO 2023-10-05 18:01:53,099 basehttp 8676 1856 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 15350
INFO 2023-10-05 18:02:13,276 basehttp 8676 1856 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 12588
INFO 2023-10-05 18:02:14,240 basehttp 8676 1856 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 12588
INFO 2023-10-05 18:02:14,788 basehttp 8676 1856 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 12588
INFO 2023-10-05 18:02:23,223 basehttp 8676 1856 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 4396
ERROR 2023-10-05 18:04:01,020 log 8676 6076 Internal Server Error: /les2/all_orders_sorted/30/10/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 40, in all_orders_sorted
    return render(request, 'myapp2/all_orders_sorted.html', {'user': user,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 21: 'endfor', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2023-10-05 18:04:01,020 basehttp 8676 6076 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 500 184944
ERROR 2023-10-05 18:04:50,085 log 8676 9980 Internal Server Error: /les2/all_orders_sorted/30/10/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 40, in all_orders_sorted
    return render(request, 'myapp2/all_orders_sorted.html', {'user': user,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 21: 'endfor', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2023-10-05 18:04:50,085 basehttp 8676 9980 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 500 185079
ERROR 2023-10-05 18:04:51,209 log 8676 9980 Internal Server Error: /les2/all_orders_sorted/30/10/
Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py", line 40, in all_orders_sorted
    return render(request, 'myapp2/all_orders_sorted.html', {'user': user,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\msv99\Desktop\Python\Django\Homework\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 21: 'endfor', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2023-10-05 18:04:51,219 basehttp 8676 9980 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 500 185079
INFO 2023-10-05 18:05:06,216 basehttp 8676 7640 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 6035
INFO 2023-10-05 18:06:16,542 basehttp 8676 13788 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 5997
INFO 2023-10-05 18:06:24,605 basehttp 8676 13788 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 5997
INFO 2023-10-05 18:12:13,189 basehttp 8676 1948 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 5997
INFO 2023-10-05 18:19:14,612 basehttp 8676 14964 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 5910
INFO 2023-10-05 18:19:15,562 basehttp 8676 14964 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 5910
INFO 2023-10-05 18:20:23,406 basehttp 8676 14964 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 5907
INFO 2023-10-05 18:20:52,643 basehttp 8676 14964 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 5862
INFO 2023-10-05 18:21:07,872 basehttp 8676 14964 "GET /les2/all_orders_sorted/30/1/ HTTP/1.1" 200 5862
INFO 2023-10-05 18:21:15,793 basehttp 8676 14964 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 5863
INFO 2023-10-05 18:21:52,110 autoreload 8676 12604 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\views.py changed, reloading.
INFO 2023-10-05 18:21:53,056 autoreload 6376 1108 Watching for file changes with StatReloader
INFO 2023-10-05 18:21:53,425 basehttp 6376 4000 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 5857
INFO 2023-10-05 18:21:54,123 basehttp 6376 4000 "GET /les2/all_orders_sorted/30/10/ HTTP/1.1" 200 5857
INFO 2023-10-05 18:21:57,494 basehttp 6376 4000 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 5856
INFO 2023-10-05 18:22:03,621 basehttp 6376 4000 "GET /les2/all_orders_sorted/30/1/ HTTP/1.1" 200 5856
WARNING 2023-10-05 18:22:47,366 log 6376 4000 Not Found: /test/30
WARNING 2023-10-05 18:22:47,367 basehttp 6376 4000 "GET /test/30 HTTP/1.1" 404 2534
INFO 2023-10-05 18:22:59,935 basehttp 6376 4000 "GET /les2/test/30/ HTTP/1.1" 200 2164
INFO 2023-10-05 18:23:32,588 autoreload 6376 1108 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\urls.py changed, reloading.
INFO 2023-10-05 18:23:33,672 autoreload 13808 1968 Watching for file changes with StatReloader
INFO 2023-10-05 18:24:02,312 autoreload 13808 1968 C:\Users\msv99\Desktop\Python\Django\Homework\myapp2\urls.py changed, reloading.
INFO 2023-10-05 18:24:03,112 autoreload 7152 9240 Watching for file changes with StatReloader
INFO 2023-10-05 18:24:06,734 views 7152 4328 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-05 18:24:06,736 basehttp 7152 4328 "GET / HTTP/1.1" 200 548
INFO 2023-10-05 18:24:09,646 views 7152 4328 Показана информация: <h1>Hello, world!</h1><p>Домашнее задание №1</p><p>Создайте пару представлений в вашем первом приложении:<br>— главная<br>— о себе.<br>Внутри каждого представления должна быть переменная html — многострочный текст с HTML-вёрсткой и данными о вашем первом Django-сайте и о вас.Сохраняйте в логи данные о посещении страниц.</p>
INFO 2023-10-05 18:24:09,647 basehttp 7152 4328 "GET / HTTP/1.1" 200 548
INFO 2023-10-05 18:24:23,973 basehttp 7152 4328 "GET /les2/all_orders_sorted/30/7/ HTTP/1.1" 200 5856
INFO 2023-10-05 18:24:35,818 basehttp 7152 4328 "GET /les2/all_orders/30/ HTTP/1.1" 200 12336
